/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import kalah.bol.client.domain.Player;

/**
 * Action
 */

public class Action {
  @JsonProperty("player")
  private Player player = null;

  @JsonProperty("pitIndex")
  private Integer pitIndex;

  public Action player(Player player) {
    this.player = player;
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @ApiModelProperty(value = "")
  public Player getPlayer() {
    return player;
  }

  public void setPlayer(Player player) {
    this.player = player;
  }

  public Action pitIndex(Integer pitIndex) {
    this.pitIndex = pitIndex;
    return this;
  }

   /**
   * Get pitIndex
   * minimum: 0
   * @return pitIndex
  **/
  @ApiModelProperty(value = "")
  public Integer getPitIndex() {
    return pitIndex;
  }

  public void setPitIndex(Integer pitIndex) {
    this.pitIndex = pitIndex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Action action = (Action) o;
    return Objects.equals(this.player, action.player) &&
        Objects.equals(this.pitIndex, action.pitIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(player, pitIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Action {\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    pitIndex: ").append(toIndentedString(pitIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

