/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import kalah.bol.client.domain.Pit;

/**
 * Board
 */

public class Board {
  @JsonProperty("pits")
  private List<Pit> pits = new ArrayList<Pit>();

  public Board pits(List<Pit> pits) {
    this.pits = pits;
    return this;
  }

  public Board addPitsItem(Pit pitsItem) {
    if (this.pits == null) {
      this.pits = new ArrayList<Pit>();
    }
    this.pits.add(pitsItem);
    return this;
  }

   /**
   * Lists all the pits from the board
   * @return pits
  **/
  @ApiModelProperty(value = "Lists all the pits from the board")
  public List<Pit> getPits() {
    return pits;
  }

  public void setPits(List<Pit> pits) {
    this.pits = pits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Board board = (Board) o;
    return Objects.equals(this.pits, board.pits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Board {\n");
    sb.append("    pits: ").append(toIndentedString(pits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

