/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import kalah.bol.client.domain.Board;
import kalah.bol.client.domain.Pit;
import kalah.bol.client.domain.Player;
import kalah.bol.client.domain.Turn;
import kalah.bol.client.domain.VictoryState;

/**
 * GameState
 */

public class GameState {
  @JsonProperty("board")
  private Board board = null;

  @JsonProperty("currentPlayer")
  private Player currentPlayer = null;

  @JsonProperty("currentIndex")
  private Integer currentIndex;

  @JsonProperty("remainingPieces")
  private Integer remainingPieces;

  @JsonProperty("currentPit")
  private Pit currentPit = null;

  @JsonProperty("currentTurn")
  private Turn currentTurn;

  @JsonProperty("currentVictory")
  private VictoryState currentVictory;

  public GameState board(Board board) {
    this.board = board;
    return this;
  }

   /**
   * Get board
   * @return board
  **/
  @ApiModelProperty(value = "")
  public Board getBoard() {
    return board;
  }

  public void setBoard(Board board) {
    this.board = board;
  }

  public GameState currentPlayer(Player currentPlayer) {
    this.currentPlayer = currentPlayer;
    return this;
  }

   /**
   * Get currentPlayer
   * @return currentPlayer
  **/
  @ApiModelProperty(value = "")
  public Player getCurrentPlayer() {
    return currentPlayer;
  }

  public void setCurrentPlayer(Player currentPlayer) {
    this.currentPlayer = currentPlayer;
  }

  public GameState currentIndex(Integer currentIndex) {
    this.currentIndex = currentIndex;
    return this;
  }

   /**
   * Get currentIndex
   * @return currentIndex
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrentIndex() {
    return currentIndex;
  }

  public void setCurrentIndex(Integer currentIndex) {
    this.currentIndex = currentIndex;
  }

  public GameState remainingPieces(Integer remainingPieces) {
    this.remainingPieces = remainingPieces;
    return this;
  }

   /**
   * Get remainingPieces
   * @return remainingPieces
  **/
  @ApiModelProperty(value = "")
  public Integer getRemainingPieces() {
    return remainingPieces;
  }

  public void setRemainingPieces(Integer remainingPieces) {
    this.remainingPieces = remainingPieces;
  }

  public GameState currentPit(Pit currentPit) {
    this.currentPit = currentPit;
    return this;
  }

   /**
   * Get currentPit
   * @return currentPit
  **/
  @ApiModelProperty(value = "")
  public Pit getCurrentPit() {
    return currentPit;
  }

  public void setCurrentPit(Pit currentPit) {
    this.currentPit = currentPit;
  }

  public GameState currentTurn(Turn currentTurn) {
    this.currentTurn = currentTurn;
    return this;
  }

   /**
   * Get currentTurn
   * @return currentTurn
  **/
  @ApiModelProperty(value = "")
  public Turn getCurrentTurn() {
    return currentTurn;
  }

  public void setCurrentTurn(Turn currentTurn) {
    this.currentTurn = currentTurn;
  }

  public GameState currentVictory(VictoryState currentVictory) {
    this.currentVictory = currentVictory;
    return this;
  }

   /**
   * Get currentVictory
   * @return currentVictory
  **/
  @ApiModelProperty(value = "")
  public VictoryState getCurrentVictory() {
    return currentVictory;
  }

  public void setCurrentVictory(VictoryState currentVictory) {
    this.currentVictory = currentVictory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameState gameState = (GameState) o;
    return Objects.equals(this.board, gameState.board) &&
        Objects.equals(this.currentPlayer, gameState.currentPlayer) &&
        Objects.equals(this.currentIndex, gameState.currentIndex) &&
        Objects.equals(this.remainingPieces, gameState.remainingPieces) &&
        Objects.equals(this.currentPit, gameState.currentPit) &&
        Objects.equals(this.currentTurn, gameState.currentTurn) &&
        Objects.equals(this.currentVictory, gameState.currentVictory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(board, currentPlayer, currentIndex, remainingPieces, currentPit, currentTurn, currentVictory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameState {\n");
    sb.append("    board: ").append(toIndentedString(board)).append("\n");
    sb.append("    currentPlayer: ").append(toIndentedString(currentPlayer)).append("\n");
    sb.append("    currentIndex: ").append(toIndentedString(currentIndex)).append("\n");
    sb.append("    remainingPieces: ").append(toIndentedString(remainingPieces)).append("\n");
    sb.append("    currentPit: ").append(toIndentedString(currentPit)).append("\n");
    sb.append("    currentTurn: ").append(toIndentedString(currentTurn)).append("\n");
    sb.append("    currentVictory: ").append(toIndentedString(currentVictory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

