/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import kalah.bol.client.domain.Player;

/**
 * NewGameCommand
 */

public class NewGameCommand {
  @JsonProperty("firstPlayer")
  private Player firstPlayer = null;

  @JsonProperty("secondPlayer")
  private Player secondPlayer = null;

  public NewGameCommand firstPlayer(Player firstPlayer) {
    this.firstPlayer = firstPlayer;
    return this;
  }

   /**
   * Get firstPlayer
   * @return firstPlayer
  **/
  @ApiModelProperty(value = "")
  public Player getFirstPlayer() {
    return firstPlayer;
  }

  public void setFirstPlayer(Player firstPlayer) {
    this.firstPlayer = firstPlayer;
  }

  public NewGameCommand secondPlayer(Player secondPlayer) {
    this.secondPlayer = secondPlayer;
    return this;
  }

   /**
   * Get secondPlayer
   * @return secondPlayer
  **/
  @ApiModelProperty(value = "")
  public Player getSecondPlayer() {
    return secondPlayer;
  }

  public void setSecondPlayer(Player secondPlayer) {
    this.secondPlayer = secondPlayer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewGameCommand newGameCommand = (NewGameCommand) o;
    return Objects.equals(this.firstPlayer, newGameCommand.firstPlayer) &&
        Objects.equals(this.secondPlayer, newGameCommand.secondPlayer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstPlayer, secondPlayer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewGameCommand {\n");
    sb.append("    firstPlayer: ").append(toIndentedString(firstPlayer)).append("\n");
    sb.append("    secondPlayer: ").append(toIndentedString(secondPlayer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

