/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import kalah.bol.client.domain.Player;

/**
 * Pit
 */

public class Pit {
  @JsonProperty("pieces")
  private Integer pieces;

  @JsonProperty("player")
  private Player player = null;

  @JsonProperty("store")
  private Boolean store;

  public Pit pieces(Integer pieces) {
    this.pieces = pieces;
    return this;
  }

   /**
   * Get pieces
   * @return pieces
  **/
  @ApiModelProperty(value = "")
  public Integer getPieces() {
    return pieces;
  }

  public void setPieces(Integer pieces) {
    this.pieces = pieces;
  }

  public Pit player(Player player) {
    this.player = player;
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @ApiModelProperty(value = "")
  public Player getPlayer() {
    return player;
  }

  public void setPlayer(Player player) {
    this.player = player;
  }

  public Pit store(Boolean store) {
    this.store = store;
    return this;
  }

   /**
   * Get store
   * @return store
  **/
  @ApiModelProperty(value = "")
  public Boolean getStore() {
    return store;
  }

  public void setStore(Boolean store) {
    this.store = store;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pit pit = (Pit) o;
    return Objects.equals(this.pieces, pit.pieces) &&
        Objects.equals(this.player, pit.player) &&
        Objects.equals(this.store, pit.store);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pieces, player, store);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pit {\n");
    sb.append("    pieces: ").append(toIndentedString(pieces)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    store: ").append(toIndentedString(store)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

