/*
 * Bol Kalah
 * The Kalah Game for Bol Assessment
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ygorcastor@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package kalah.bol.client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import kalah.bol.client.domain.Game;

/**
 * Session
 */

public class Session {
  @JsonProperty("sessionId")
  private String sessionId;

  @JsonProperty("game")
  private Game game = null;

  public Session sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Gets session id.
   * @return sessionId
  **/
  @ApiModelProperty(value = "Gets session id.")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public Session game(Game game) {
    this.game = game;
    return this;
  }

   /**
   * Get game
   * @return game
  **/
  @ApiModelProperty(value = "")
  public Game getGame() {
    return game;
  }

  public void setGame(Game game) {
    this.game = game;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Session session = (Session) o;
    return Objects.equals(this.sessionId, session.sessionId) &&
        Objects.equals(this.game, session.game);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionId, game);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Session {\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    game: ").append(toIndentedString(game)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

